name: Release Notes
on:
  push:
    branches:
      - 'main'
jobs:
  run_sls:
    name: SLS
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: echo "npm install"
      - name: Invoke
        run: echo "sls invoke local -f harvey"
   